# Generated by Django 3.1.7 on 2021-05-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collab_Project', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='post',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
