# Generated by Django 3.1.7 on 2021-05-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collab_Project', '0005_auto_20210508_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='Message',
            field=models.TextField(max_length=30),
        ),
    ]
