# Generated by Django 3.1.7 on 2021-05-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collab_Project', '0006_auto_20210508_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='Message',
            field=models.TextField(),
        ),
    ]
