# Generated by Django 3.1.7 on 2021-05-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collab_Project', '0009_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='desc',
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.TextField(),
        ),
    ]
