# Generated by Django 3.1.7 on 2021-05-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collab_Project', '0010_auto_20210510_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
